/**
 * Type declarations for `.aktion` modules, so `.aktion.ts` code can import from
 * them with types (guide §7.10).
 *
 * TypeScript knows nothing about `.aktion` files: `import { TodoRow } from
 * "./todo-row.aktion"` fails with TS2614 against the ambient `*.aktion`
 * wildcard. With `allowArbitraryExtensions`, TypeScript resolves that import to
 * a sibling `todo-row.d.aktion.ts` first — so this module writes one per
 * `.aktion` file, declaring what it exports:
 *
 *   - a component as a function of optional `any` parameters plus `...rest`
 *     (components also take a trailing named-props object and extra children);
 *   - an action with one optional `any` per parameter, so arity is checked;
 *   - a hook as `(...args: any[]) => any`;
 *   - an atom or plain binding with the primitive type of a literal
 *     initializer, `any` otherwise;
 *   - always a default export typed as the `CompiledProgram` the Vite plugin
 *     produces, so `import app from "./app.aktion"` stays typed.
 *
 * The declarations can live outside the source tree: with the default `outDir`
 * (`.aktion-types`), add `"rootDirs": ["src", ".aktion-types/src"]` to the
 * tsconfig. `.aktion.js` / `.aktion.ts` modules need no declarations — with
 * `allowJs`, TypeScript reads them directly.
 *
 * Node-only (it reads and writes files).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { parse } from "../parser/index.js";
import type { DeclParam, Expression, ParseError, Statement } from "../parser/types.js";

/** First line of every generated file — how stale ones are recognised and removed. */
export const DECLARATION_HEADER = "// Generated by aktion-dts";

/** Where declarations go by default, relative to `root`. */
export const DEFAULT_DECLARATIONS_DIR = ".aktion-types";

/** Directories never searched for `.aktion` modules. */
const SKIPPED_DIRECTORIES = new Set(["node_modules", ".git", "dist"]);

export interface AktionDeclarationsOptions {
  /** Project root; `include`, `exclude` and `outDir` are relative to it. Default: `process.cwd()`. */
  root?: string;
  /** Globs of `.aktion` modules to declare. Default: `["src/**\/*.aktion"]`. */
  include?: string[];
  /** Globs to leave out. */
  exclude?: string[];
  /**
   * Directory the declarations are written to, mirroring the modules' paths.
   * Default: `.aktion-types`. Pass the root itself (`"."`) to write each one
   * next to its module.
   */
  outDir?: string;
  /** `false` computes the result without touching the disk (`aktion-dts --check`). Default: true. */
  write?: boolean;
}

export interface AktionDeclarationsResult {
  /** Declarations created or changed (or that would be, with `write: false`). */
  written: string[];
  /** Declarations already up to date. */
  unchanged: string[];
  /** Generated declarations whose module no longer exists, removed. */
  removed: string[];
  /** Parse errors of the modules (declared as far as they parsed). */
  diagnostics: Array<{ path: string; line: number; column: number; message: string }>;
}

/* -------------------------------------------------------------------------- */
/*  One module                                                                 */
/* -------------------------------------------------------------------------- */

/** `todo-row.aktion` → `todo-row.d.aktion.ts`, the name TypeScript looks up for `./todo-row.aktion`. */
export function declarationFileName(modulePath: string): string {
  return modulePath.replace(/\.aktion$/i, ".d.aktion.ts");
}

/** The declaration text for one `.aktion` module, and the parse errors it had. */
export function aktionDeclarationText(
  source: string,
  sourceName = "module.aktion",
): { text: string; errors: ParseError[] } {
  const program = parse(source);
  const lines: string[] = [];
  let usesNode = false;
  for (const stmt of program.statements) {
    const line = declare(stmt);
    if (line === null) continue;
    if (line.includes("AktionNode")) usesNode = true;
    lines.push(line);
  }
  const types = usesNode ? "AktionNode, CompiledProgram" : "CompiledProgram";
  const text = [
    `${DECLARATION_HEADER} from ${sourceName} — do not edit.`,
    `import type { ${types} } from "aktion-runtime/dsl";`,
    "",
    ...lines,
    ...(lines.length > 0 ? [""] : []),
    "declare const compiled: CompiledProgram;",
    "export default compiled;",
    "",
  ].join("\n");
  return { text, errors: program.errors };
}

function declare(stmt: Statement): string | null {
  switch (stmt.kind) {
    case "ComponentDeclaration":
      if (!stmt.exported) return null;
      return `export declare function ${stmt.name}(${parameters(stmt.params, true)}): AktionNode;`;
    case "ActionDeclaration":
      if (!stmt.exported) return null;
      return `export declare function ${stmt.name}(${parameters(stmt.params, false)}): any;`;
    case "HookDeclaration":
      if (!stmt.exported) return null;
      return `export declare function $${stmt.name}(...args: any[]): any;`;
    case "Assignment": {
      if (!stmt.exported) return null;
      if (stmt.isState) return `export declare let $${stmt.identifier}: ${valueType(stmt.expression)};`;
      const keyword = stmt.declaration === "let" || stmt.declaration === "var" ? "let" : "const";
      return `export declare ${keyword} ${stmt.identifier}: ${valueType(stmt.expression)};`;
    }
    default:
      return null;
  }
}

/** One optional `any` per declared parameter (`p{i}` for a pattern), a rest parameter as `...name: any[]`. */
function parameters(params: ReadonlyArray<DeclParam>, component: boolean): string {
  const names = new Set<string>();
  const out = params.map((p, i) => {
    const name = p.name || `p${i}`;
    names.add(name);
    return p.rest ? `...${name}: any[]` : `${name}?: any`;
  });
  // Components also take a trailing named-props object and extra children.
  if (component && !params.some((p) => p.rest)) {
    let rest = "rest";
    while (names.has(rest)) rest = `_${rest}`;
    out.push(`...${rest}: any[]`);
  }
  return out.join(", ");
}

/** The primitive type of a literal initializer; `any` for everything else. */
function valueType(expr: Expression): string {
  switch (expr.kind) {
    case "Literal":
      return typeof expr.value === "string" || typeof expr.value === "number" || typeof expr.value === "boolean"
        ? typeof expr.value
        : "any";
    case "Template":
      return "string";
    case "Unary":
      if ((expr.operator === "-" || expr.operator === "+") && expr.argument.kind === "Literal" && typeof expr.argument.value === "number") {
        return "number";
      }
      return expr.operator === "!" ? "boolean" : "any";
    case "Lambda":
      return "(...args: any[]) => any";
    default:
      return "any";
  }
}

/* -------------------------------------------------------------------------- */
/*  A project                                                                  */
/* -------------------------------------------------------------------------- */

/** A glob (`src/**\/*.aktion`) as an anchored RegExp over `/`-separated relative paths. */
function globToRegExp(glob: string): RegExp {
  let re = "";
  for (let i = 0; i < glob.length; i += 1) {
    const ch = glob[i]!;
    if (ch === "*") {
      if (glob[i + 1] === "*") {
        const slash = glob[i + 2] === "/";
        re += slash ? "(?:.*/)?" : ".*";
        i += slash ? 2 : 1;
      } else {
        re += "[^/]*";
      }
    } else if (ch === "?") {
      re += "[^/]";
    } else {
      re += /[\\^$.|+()[\]{}]/.test(ch) ? `\\${ch}` : ch;
    }
  }
  return new RegExp(`^${re}$`);
}

const toPosix = (p: string): string => p.split(sep).join("/");

function walkFiles(dir: string, skip: ReadonlySet<string>, out: string[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const name of entries) {
    const full = join(dir, name);
    if (skip.has(full)) continue;
    let stats;
    try {
      stats = statSync(full);
    } catch {
      continue;
    }
    if (stats.isDirectory()) {
      if (!SKIPPED_DIRECTORIES.has(name)) walkFiles(full, skip, out);
    } else if (stats.isFile()) {
      out.push(full);
    }
  }
}

interface Resolved {
  root: string;
  outDir: string;
  include: RegExp[];
  exclude: RegExp[];
  write: boolean;
}

function resolveOptions(options: AktionDeclarationsOptions): Resolved {
  const root = resolve(options.root ?? process.cwd());
  return {
    root,
    outDir: resolve(root, options.outDir ?? DEFAULT_DECLARATIONS_DIR),
    include: (options.include ?? ["src/**/*.aktion"]).map(globToRegExp),
    exclude: (options.exclude ?? []).map(globToRegExp),
    write: options.write !== false,
  };
}

function isDeclared(file: string, o: Resolved): boolean {
  if (!/\.aktion$/i.test(file)) return false;
  const rel = toPosix(relative(o.root, file));
  if (rel.startsWith("..")) return false;
  return o.include.some((re) => re.test(rel)) && !o.exclude.some((re) => re.test(rel));
}

function targetOf(file: string, o: Resolved): string {
  return join(o.outDir, declarationFileName(relative(o.root, file)));
}

function emitOne(file: string, o: Resolved, result: AktionDeclarationsResult): string {
  const target = targetOf(file, o);
  const { text, errors } = aktionDeclarationText(readFileSync(file, "utf8"), toPosix(relative(o.root, file)));
  for (const e of errors) result.diagnostics.push({ path: file, line: e.line, column: e.column, message: e.message });
  const current = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (current === text) {
    result.unchanged.push(target);
  } else {
    result.written.push(target);
    if (o.write) {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, text);
    }
  }
  return target;
}

/**
 * Write a `name.d.aktion.ts` declaration for every `.aktion` module under
 * `root` that `include` matches — only where the text changed, so a watcher
 * does not fire for nothing — and remove generated declarations whose module
 * is gone.
 */
export function emitAktionDeclarations(options: AktionDeclarationsOptions = {}): AktionDeclarationsResult {
  const o = resolveOptions(options);
  const result: AktionDeclarationsResult = { written: [], unchanged: [], removed: [], diagnostics: [] };
  const files: string[] = [];
  walkFiles(o.root, new Set([o.outDir]), files);
  const targets = new Set<string>();
  for (const file of files.sort()) if (isDeclared(file, o)) targets.add(emitOne(file, o, result));

  // Stale declarations: generated by us (the header says so), module gone.
  const existing: string[] = [];
  walkFiles(o.outDir === o.root ? o.root : o.outDir, new Set(), existing);
  for (const file of existing) {
    if (!file.endsWith(".d.aktion.ts") || targets.has(file)) continue;
    let head = "";
    try {
      head = readFileSync(file, "utf8").slice(0, DECLARATION_HEADER.length);
    } catch {
      continue;
    }
    if (head !== DECLARATION_HEADER) continue;
    result.removed.push(file);
    if (o.write) rmSync(file, { force: true });
  }
  return result;
}

/**
 * Bring one module's declaration up to date — after an edit, or remove it
 * after a deletion. Used by the Vite plugin's dev server; a module `include`
 * does not match is ignored.
 */
export function updateAktionDeclaration(file: string, options: AktionDeclarationsOptions = {}): AktionDeclarationsResult {
  const o = resolveOptions(options);
  const result: AktionDeclarationsResult = { written: [], unchanged: [], removed: [], diagnostics: [] };
  const absolute = resolve(file);
  if (!isDeclared(absolute, o)) return result;
  if (existsSync(absolute)) {
    emitOne(absolute, o, result);
  } else {
    const target = targetOf(absolute, o);
    if (existsSync(target)) {
      result.removed.push(target);
      if (o.write) rmSync(target, { force: true });
    }
  }
  return result;
}
