/**
 * Type declarations for `.aktion` modules, so `.aktion.ts` code can import from
 * them with types (guide §7.10).
 *
 * TypeScript knows nothing about `.aktion` files: `import { TodoRow } from
 * "./todo-row.aktion"` fails with TS2614 against the ambient `*.aktion`
 * wildcard. With `allowArbitraryExtensions`, TypeScript resolves that import to
 * a sibling `todo-row.d.aktion.ts` first — so this module writes one per
 * `.aktion` file, declaring what it exports:
 *
 *   - a component as one overload per way a call binds its arguments (the
 *     evaluator's `invokeComponentDecl`): its parameters positionally, then
 *     extra positionals as `children`; or a named-props object literal
 *     (`TodoRowProps`: the parameters by name, `key`, and named slots) among
 *     them, with the positionals before and after it filling the parameters in
 *     order. It returns `AktionNode<"TodoRow">`;
 *   - an action or hook with one optional parameter per declared one, so arity
 *     is checked;
 *   - a parameter with a literal default typed from it — `tone = "muted"` is
 *     `string | null`, because only `undefined` selects the default and `null`
 *     is bound as passed — and `any` otherwise;
 *   - an atom or plain binding with the type of its initializer (a literal, an
 *     array or object literal, a `$http` / `$query` / `$mutation` / … resource),
 *     widened by every other value the module writes to it — an assignment, a
 *     compound one, a write through a member — and `any` where nothing is
 *     known. Object literals that meet (array elements, successive values)
 *     merge into one shape, with a key optional where some literal lacks it;
 *   - always a default export typed as the `CompiledProgram` the Vite plugin
 *     produces, so `import app from "./app.aktion"` stays typed.
 *
 * The declarations can live outside the source tree: with the default `outDir`
 * (`.aktion-types`), add `"rootDirs": ["src", ".aktion-types/src"]` to the
 * tsconfig. Modules reached through an `alias` (a monorepo's shared library)
 * are mirrored under `outDir/<prefix>/`, which a second tsconfig `paths` entry
 * points at. `.aktion.js` / `.aktion.ts` modules need no declarations — with
 * `allowJs`, TypeScript reads them directly.
 *
 * Node-only (it reads and writes files).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { parse } from "../parser/index.js";
import { walk } from "../parser/walk.js";
import type { ArrayExpr, DeclParam, Expression, ObjectExpr, ParseError, Program, Statement } from "../parser/types.js";

/** First line of every generated file — how stale ones are recognised and removed. */
export const DECLARATION_HEADER = "// Generated by aktion-dts";

/** Where declarations go by default, relative to `root`. */
export const DEFAULT_DECLARATIONS_DIR = ".aktion-types";

/** Directories never searched for `.aktion` modules. */
const SKIPPED_DIRECTORIES = new Set(["node_modules", ".git", "dist"]);

export interface AktionDeclarationsOptions {
  /** Project root; `include`, `exclude` and `outDir` are relative to it. Default: `process.cwd()`. */
  root?: string;
  /** Globs of `.aktion` modules to declare. Default: `["src/**\/*.aktion"]`. */
  include?: string[];
  /** Globs to leave out. */
  exclude?: string[];
  /**
   * Directory the declarations are written to, mirroring the modules' paths.
   * Default: `.aktion-types`. Pass the root itself (`"."`) to write each one
   * next to its module.
   */
  outDir?: string;
  /**
   * Bare-specifier prefixes mapped to directories — the plugin's `alias`
   * option, or `aktion.config.json`'s. Every `.aktion` module under a target is
   * declared too, mirrored under `outDir/<prefix>/` (under `.aktion-types/<prefix>/`
   * when `outDir` is the root), so `import { Badge } from "@acme/ui/badge.aktion"`
   * type-checks with a second tsconfig `paths` entry:
   * `"@acme/ui/*": ["../../libs/ui/src/*", "./.aktion-types/@acme/ui/*"]`.
   * Relative targets resolve against `root`.
   */
  alias?: Record<string, string>;
  /** `false` computes the result without touching the disk (`aktion-dts --check`). Default: true. */
  write?: boolean;
}

export interface AktionDeclarationsResult {
  /** Declarations created or changed (or that would be, with `write: false`). */
  written: string[];
  /** Declarations already up to date. */
  unchanged: string[];
  /** Generated declarations whose module no longer exists, removed. */
  removed: string[];
  /** Parse errors of the modules (declared as far as they parsed). */
  diagnostics: Array<{ path: string; line: number; column: number; message: string }>;
  /** Options that cannot do what they say — an `include` glob that leaves the root, an unusable alias prefix. */
  warnings: string[];
}

/* -------------------------------------------------------------------------- */
/*  One module                                                                 */
/* -------------------------------------------------------------------------- */

/** `todo-row.aktion` → `todo-row.d.aktion.ts`, the name TypeScript looks up for `./todo-row.aktion`. */
export function declarationFileName(modulePath: string): string {
  return modulePath.replace(/\.aktion$/i, ".d.aktion.ts");
}

/** Names TypeScript does not accept as a binding (a parameter or a declared const). */
const RESERVED_WORDS = new Set(
  (
    "break case catch class const continue debugger default delete do else enum export extends false finally for " +
    "function if implements import in instanceof interface let new null package private protected public return " +
    "static super switch this throw true try typeof var void while with yield await"
  ).split(" "),
);

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/** A property name as written in a type literal: bare when it is an identifier, quoted otherwise. */
const propertyName = (key: string): string => (IDENTIFIER.test(key) ? key : JSON.stringify(key));

/** One exported binding of a module: its TypeScript name, and the lines that declare it. */
interface Declared {
  name: string;
  lines: string[];
  /** `aktion-runtime/dsl` types the lines mention. */
  uses: Set<string>;
}

/**
 * The names an Aktion module exports, as host code would import them: `$count`
 * for an atom or hook, `TodoRow` for a component, action or plain binding. A
 * later top-level declaration of a name replaces an earlier one, as it does at
 * runtime.
 */
export function aktionExportNames(program: Program): string[] {
  const names = new Set<string>();
  const listed = listedExports(program);
  for (const stmt of program.statements) {
    for (const name of exportNames(stmt, listed)) names.add(name);
    if (stmt.kind === "ExportList" && stmt.source !== undefined) {
      for (const spec of stmt.specifiers) names.add(spec.isState ? `$${spec.exported}` : spec.exported);
    }
  }
  return [...names];
}

/** The binding key of a declaration — `$count` for an atom or hook, `TodoRow` otherwise — or `null` for a statement that declares none. */
function declaredKey(stmt: Statement): string | null {
  switch (stmt.kind) {
    case "ComponentDeclaration":
    case "ActionDeclaration":
      return stmt.name;
    case "HookDeclaration":
      return `$${stmt.name}`;
    case "Assignment":
      return stmt.isState ? `$${stmt.identifier}` : stmt.identifier;
    default:
      return null;
  }
}

/** Local binding key → the names an `export { … }` list gives it (no `from`; those are forwarded as written). */
function listedExports(program: Program): Map<string, string[]> {
  const listed = new Map<string, string[]>();
  for (const stmt of program.statements) {
    if (stmt.kind !== "ExportList" || stmt.source !== undefined) continue;
    for (const spec of stmt.specifiers) {
      const key = spec.isState ? `$${spec.local}` : spec.local;
      listed.set(key, [...(listed.get(key) ?? []), spec.isState ? `$${spec.exported}` : spec.exported]);
    }
  }
  return listed;
}

/** The names a statement is exported under: its own, when it carries `export`, plus every `export { … }` entry for it. */
function exportNames(stmt: Statement, listed: ReadonlyMap<string, string[]>): string[] {
  const key = declaredKey(stmt);
  if (key === null) return [];
  const own = "exported" in stmt && stmt.exported ? [key] : [];
  return [...new Set([...own, ...(listed.get(key) ?? [])])];
}

/** The declaration text for one `.aktion` module, and the parse errors it had. */
export function aktionDeclarationText(
  source: string,
  sourceName = "module.aktion",
): { text: string; errors: ParseError[] } {
  const program = parse(source);
  const assigned = assignedValues(program);
  // Local (non-exported) names the declarations introduce must not collide
  // with an export — nor with each other.
  const taken = new Set(aktionExportNames(program));
  // Last declaration of a name wins, as top-level re-binding does at runtime —
  // two declarations of one name would be TS2451 / TS2300.
  const byName = new Map<string, Declared>();
  const listed = listedExports(program);
  for (const stmt of program.statements) {
    for (const name of exportNames(stmt, listed)) {
      const declared = declare(stmt, name, assigned, taken);
      if (declared === null) continue;
      byName.delete(declared.name);
      byName.set(declared.name, declared);
    }
  }
  // A re-export is declared by pointing at the other module's own declaration
  // file, which TypeScript finds through `allowArbitraryExtensions`.
  const forwarded: string[] = [];
  for (const stmt of program.statements) {
    if (stmt.kind !== "ExportList" || stmt.source === undefined) continue;
    if (stmt.all) {
      forwarded.push(`export * from ${JSON.stringify(stmt.source)};`);
      continue;
    }
    const specs = stmt.specifiers.map((s) => {
      const local = s.isState ? `$${s.local}` : s.local;
      return s.exported === s.local ? local : `${local} as ${s.isState ? `$${s.exported}` : s.exported}`;
    });
    forwarded.push(`export { ${specs.join(", ")} } from ${JSON.stringify(stmt.source)};`);
  }

  const uses = new Set<string>(["CompiledProgram"]);
  const lines: string[] = [];
  for (const declared of byName.values()) {
    for (const type of declared.uses) uses.add(type);
    lines.push(...declared.lines);
  }
  const local = unusedName("compiled", taken);

  const text = [
    `${DECLARATION_HEADER} from ${sourceName} — do not edit.`,
    `import type { ${[...uses].sort().join(", ")} } from "aktion-runtime/dsl";`,
    "",
    ...lines,
    ...forwarded,
    ...(lines.length + forwarded.length > 0 ? [""] : []),
    `declare const ${local}: CompiledProgram;`,
    `export default ${local};`,
    "",
  ].join("\n");
  return { text, errors: program.errors };
}

function declare(
  stmt: Statement,
  name: string,
  assigned: ReadonlyMap<string, Written[]>,
  taken: Set<string>,
): Declared | null {
  const uses = new Set<string>();
  switch (stmt.kind) {
    case "ComponentDeclaration":
      return { name, lines: componentOverloads(name, stmt.params, uses, stmt.name), uses };
    case "ActionDeclaration":
    case "HookDeclaration":
      return { name, lines: [`export declare function ${name}(${parameterList(stmt.params)}): any;`], uses };
    case "Assignment": {
      const mutable = stmt.isState || stmt.declaration === "let" || stmt.declaration === "var";
      const type = mutable ? bindingType(stmt.expression, assigned.get(declaredKey(stmt)!) ?? [], uses) : valueType(stmt.expression, uses);
      return { name, lines: exportBinding(name, mutable ? "let" : "const", type, taken), uses };
    }
    default:
      return null;
  }
}

/** `base`, or `_base`, `__base`, … — the first not in `taken`, which it is then added to. */
function unusedName(base: string, taken: Set<string>): string {
  let name = base;
  while (taken.has(name) || RESERVED_WORDS.has(name)) name = `_${name}`;
  taken.add(name);
  return name;
}

/** `export declare let name: T;` — through a local alias when `name` is a reserved word (`export class = 1`). */
function exportBinding(name: string, keyword: "let" | "const", type: string, taken: Set<string>): string[] {
  if (!RESERVED_WORDS.has(name)) return [`export declare ${keyword} ${name}: ${type};`];
  const local = unusedName(name, taken);
  return [`declare ${keyword} ${local}: ${type};`, `export { ${local} as ${name} };`];
}

/* ---- parameters ---- */

/**
 * The name each parameter is declared under: its own, or `p{i}` for a
 * destructuring pattern — made unique against the real names, so
 * `({ a }, p0)` does not declare `p0` twice — and `_`-prefixed when TypeScript
 * reserves it.
 */
function parameterNames(params: ReadonlyArray<DeclParam>): string[] {
  const taken = new Set(params.map((p) => p.name).filter((n) => n !== ""));
  return params.map((p, i) => {
    let name = p.name || `p${i}`;
    if (p.name !== "" && !RESERVED_WORDS.has(name)) return name;
    while (taken.has(name) || RESERVED_WORDS.has(name)) name = `_${name}`;
    taken.add(name);
    return name;
  });
}

/**
 * A parameter's type: the primitive of a literal default plus `null` (only
 * `undefined` selects the default; `null` is bound as passed), `any` for
 * everything else. Object and array defaults stay `any`: an object literal
 * passed in their place is checked for excess properties, which the runtime
 * never rejects.
 */
function parameterType(param: DeclParam): string {
  if (param.pattern || !param.defaultValue) return "any";
  const type = valueType(param.defaultValue, new Set());
  return type === "string" || type === "number" || type === "boolean" ? `${type} | null` : "any";
}

/** `T | undefined` — the type of an optional parameter given in a position that must be filled. */
const optionalType = (type: string): string => (type === "any" ? "any" : `${type} | undefined`);

/** One optional parameter per declared one, so arity is checked; a rest parameter as `...name: any[]`. */
function parameterList(params: ReadonlyArray<DeclParam>): string {
  const names = parameterNames(params);
  return params.map((p, i) => (p.rest ? `...${names[i]}: any[]` : `${names[i]}?: ${parameterType(p)}`)).join(", ");
}

/**
 * The overloads of a component, mirroring how `invokeComponentDecl` binds a
 * call. The named props are the RIGHTMOST object literal, and only when one of
 * its keys is `key` or a parameter's name — or every parameter is already
 * filled positionally, which makes its keys named slots. Every other argument
 * is positional, wherever it stands: the positionals fill the parameters in
 * order, before the props or after them, and those past the last parameter are
 * `children`. So:
 *
 *   1. positional: each parameter, then extra positionals as `children`;
 *   2. for each count `m` of parameters filled positionally, and each split of
 *      those `m` around the props (`k` before, `m - k` after): props that name
 *      `key` or one of the parameters not filled (a parameter given positionally
 *      AND by name loses the positional value, so the props may not name it);
 *      children follow only once `m` fills every parameter;
 *   3. every parameter, children, and the props last.
 *
 * Any other key of the props is a named slot (`slots.header`), hence the index
 * signature. Types cannot tell an object literal from an object value, which
 * leaves two calls accepted as the wrong binding: props in a position whose
 * parameter is `any` read as that parameter (`Pill({ key: 1 }, "h", 42)` binds
 * `label: "h", tone: 42`), and a literal positional after the props is the
 * rightmost literal itself, and takes their place. A component with a rest
 * parameter keeps a single permissive positional form: the runtime binds its
 * rest parameter to one value.
 */
function componentOverloads(name: string, params: ReadonlyArray<DeclParam>, uses: Set<string>, tag = name): string[] {
  uses.add("AktionNode");
  const result = `AktionNode<${JSON.stringify(tag)}>`;
  const names = parameterNames(params);
  const types = params.map(parameterType);
  if (params.some((p) => p.rest)) {
    const list = params.map((p, i) => (p.rest ? `...${names[i]}: any[]` : `${names[i]}?: ${types[i]}`)).join(", ");
    return [`export declare function ${name}(${list}): ${result};`];
  }
  uses.add("Children");
  uses.add("Key");

  // The overloads' own parameter names must not repeat a real one (TS2300).
  let children = "children";
  while (names.includes(children)) children = `_${children}`;
  let propsName = "props";
  while (names.includes(propsName) || propsName === children) propsName = `_${propsName}`;
  const rest = `...${children}: Children[]`;
  // The name a caller uses for each parameter; a pattern has none, and a
  // parameter named `key` is unreachable by name (`key` is the identity).
  const keys = params.map((p) => (p.pattern || (p.publicName ?? p.name) === "key" ? null : (p.publicName ?? p.name)));
  const props = `${name}Props`;
  /** Parameters `from`..`to - 1`, each given positionally (possibly as `undefined`). */
  const given = (from: number, to: number): string[] =>
    names.slice(from, to).map((n, i) => `${n}: ${optionalType(types[from + i]!)}`);
  /** The props when the first `m` parameters are filled positionally. */
  const bag = (m: number): string => {
    const parts = [props];
    const repeated = keys.slice(0, m).filter((key): key is string => key !== null);
    if (repeated.length > 0) parts.push(`{ ${repeated.map((key) => `readonly ${propertyName(key)}?: never`).join("; ")} }`);
    if (m < params.length) {
      const members = ["{ readonly key: Key }"];
      for (let i = m; i < params.length; i += 1) {
        const key = keys[i];
        if (key !== null && key !== undefined) members.push(`{ readonly ${propertyName(key)}: ${optionalType(types[i]!)} }`);
      }
      parts.push(members.length === 1 ? members[0]! : `(${members.join(" | ")})`);
    }
    return parts.join(" & ");
  };

  const lines = [
    `/** Named props of \`${name}\`: its parameters by name, \`key\`, and named slots (any other key). */`,
    `export interface ${props} {`,
    "  readonly key?: Key;",
    ...keys.flatMap((key, i) => (key === null ? [] : [`  readonly ${propertyName(key)}?: ${types[i]};`])),
    "  readonly [slot: string]: unknown;",
    "}",
    `export declare function ${name}(${[...names.map((n, i) => `${n}?: ${types[i]}`), rest].join(", ")}): ${result};`,
  ];
  for (let m = 0; m <= params.length; m += 1) {
    for (let k = 0; k <= m; k += 1) {
      const list = [...given(0, k), `${propsName}: ${bag(m)}`, ...given(k, m)];
      if (m === params.length) list.push(rest);
      lines.push(`export declare function ${name}(${list.join(", ")}): ${result};`);
    }
  }
  lines.push(
    `export declare function ${name}(...args: [${[...given(0, params.length), rest, `${propsName}: ${bag(params.length)}`].join(", ")}]): ${result};`,
  );
  return lines;
}

/* ---- values ---- */

/** Resource builtins and the `aktion-runtime/dsl` type of the handle each returns. */
const RESOURCE_TYPES: Readonly<Record<string, string>> = {
  http: "HttpResource",
  mutation: "MutationResource",
  socket: "SocketResource",
  sse: "SseResource",
  script: "ScriptResource",
};

const PRIMITIVES = new Set(["string", "number", "boolean"]);

/** A function type inside a union or an array needs parentheses. */
const grouped = (type: string): string => (type.startsWith("(") && type.includes("=>") ? `(${type})` : type);

/**
 * The type of an expression whose type the source states — a literal, a
 * template, an array or object literal, a resource factory — and `any` for
 * everything else. `null` is `"null"`; callers decide what it widens.
 */
function valueType(expr: Expression, uses: Set<string>): string {
  switch (expr.kind) {
    case "Literal":
      if (expr.value === null) return "null";
      return typeof expr.value === "string" || typeof expr.value === "number" || typeof expr.value === "boolean"
        ? typeof expr.value
        : "any";
    case "Template":
      return "string";
    case "Unary":
      if ((expr.operator === "-" || expr.operator === "+") && expr.argument.kind === "Literal" && typeof expr.argument.value === "number") {
        return "number";
      }
      return expr.operator === "!" ? "boolean" : "any";
    case "Lambda":
      return "(...args: any[]) => any";
    case "Array":
      return arrayType([expr], uses);
    case "Object":
      return isShape(expr) ? objectType([expr], uses) : "any";
    case "Invoke":
      return expr.callee.kind === "StateRef" ? resourceType(expr.callee.name, expr.arguments, uses) : "any";
    default:
      return "any";
  }
}

/** An object literal whose keys the source states: no spread, no computed key. */
const isShape = (expr: ObjectExpr): boolean => expr.properties.every((p) => !p.spread && !p.computedKey);

/**
 * The types a value can have when it is one of `exprs`, in source order. Object
 * literals merge into one shape and array literals into one array, so
 * `[{ id: 1 }, { id: 2, done: true }]` reads as `{ id: number; done?: boolean }`
 * — a union of the two would reject `t.done`, which the runtime reads as
 * `undefined` or `true`.
 */
function unionTypes(exprs: readonly Expression[], uses: Set<string>): string[] {
  const objects: ObjectExpr[] = [];
  const arrays: ArrayExpr[] = [];
  // Each list stands where its first literal does, for the merged type.
  const slots: Array<string | ObjectExpr[] | ArrayExpr[]> = [];
  for (const expr of exprs) {
    if (expr.kind === "Object" && isShape(expr)) {
      if (objects.length === 0) slots.push(objects);
      objects.push(expr);
    } else if (expr.kind === "Array") {
      if (arrays.length === 0) slots.push(arrays);
      arrays.push(expr);
    } else {
      slots.push(valueType(expr, uses));
    }
  }
  const types = slots.map((slot) =>
    typeof slot === "string" ? slot : slot === objects ? objectType(objects, uses) : arrayType(arrays, uses),
  );
  return [...new Set(types)];
}

/** One array type for every element of `arrays`; `any[]` when one is empty or spreads, or an element is unknown. */
function arrayType(arrays: readonly ArrayExpr[], uses: Set<string>): string {
  const elements = arrays.flatMap((a) => a.elements);
  if (arrays.some((a) => a.elements.length === 0) || elements.some((e) => e.kind === "Spread")) return "any[]";
  const union = unionTypes(elements, uses);
  if (union.includes("any")) return "any[]";
  return union.length === 1 && IDENTIFIER.test(union[0]!) ? `${union[0]}[]` : `Array<${union.map(grouped).join(" | ")}>`;
}

/**
 * One object type for every literal in `objects`: each key typed by all its
 * values, and optional where some literal lacks it. A key that is only ever
 * `null` is `any` — a placeholder whose real type the source does not state.
 */
function objectType(objects: readonly ObjectExpr[], uses: Set<string>): string {
  const values = new Map<string, Expression[]>();
  for (const obj of objects) {
    for (const prop of obj.properties) {
      const list = values.get(prop.key) ?? [];
      list.push(prop.value);
      values.set(prop.key, list);
    }
  }
  if (values.size === 0) return "Record<string, any>";
  const fields: string[] = [];
  for (const [key, exprs] of values) {
    const optional = objects.some((obj) => !obj.properties.some((p) => p.key === key));
    fields.push(`${propertyName(key)}${optional ? "?" : ""}: ${withNull(unionTypes(exprs, uses))}`);
  }
  return `{ ${fields.join("; ")} }`;
}

/** A union with `null` last; `any` when a member is unknown or `null` is all there is. */
function withNull(types: readonly string[]): string {
  if (types.includes("any")) return "any";
  const known = types.filter((t) => t !== "null");
  if (known.length === 0) return "any";
  const nullable = types.includes("null");
  const ordered = known.length === 1 && !nullable ? known : known.map(grouped);
  if (nullable) ordered.push("null");
  return ordered.join(" | ");
}

/** The handle a builtin factory returns (`$http(…)` → `HttpResource<unknown>`), or `any`. */
function resourceType(builtin: string, args: ReadonlyArray<Expression>, uses: Set<string>): string {
  const config = args[0]?.kind === "Object" ? args[0] : null;
  const field = (key: string): Expression | undefined => config?.properties.find((p) => !p.spread && p.key === key)?.value;
  const use = (type: string): string => {
    uses.add(type);
    return type;
  };
  if (RESOURCE_TYPES[builtin]) return `${use(RESOURCE_TYPES[builtin]!)}<unknown>`;
  if (builtin === "query") {
    // `infinite: {…}` accumulates pages; a config held in a variable could be either.
    if (config === null || config.properties.some((p) => p.spread)) return "any";
    const infinite = field("infinite");
    const off = infinite === undefined || (infinite.kind === "Literal" && (infinite.value === null || infinite.value === false));
    return off ? `${use("HttpResource")}<unknown>` : `${use("InfiniteQueryResource")}<unknown>`;
  }
  if (builtin === "form") {
    const values = field("values");
    const shape = values?.kind === "Object" ? valueType(values, uses) : "any";
    return shape.startsWith("{ ") ? `${use("FormHandle")}<${shape}>` : use("FormHandle");
  }
  if (builtin === "i18n") return use("I18nInstance");
  if (builtin === "theme") return use("ThemeHandle");
  return "any";
}

/**
 * A value the module writes to a binding: the expression it assigns;
 * `"unknown"` when the source does not state it (`$n += step`); or `"member"`
 * for a write through a member (`$user.name = null`, `$cart.items.push(row)`),
 * which the runtime applies to whatever the binding holds — it turns a string
 * atom into an object.
 */
type Written = Expression | "unknown" | "member";

/**
 * The type of an atom or `let` binding: its initializer's, widened by every
 * value the module writes to it anywhere (`$selected = null` in an action makes
 * `number | null`). A write through a member makes the binding `any`, and so
 * does a write whose type is unknown, except for a primitive initializer, which
 * is assumed to keep its kind — `$count = $count + 1` keeps `$count` a number.
 */
function bindingType(init: Expression, writes: readonly Written[], uses: Set<string>): string {
  // Probe with a scratch set: only the final type's resource names are imported.
  const initial = valueType(init, new Set());
  if (initial === "any") return "any";
  const primitive = PRIMITIVES.has(initial);
  const known: Expression[] = [init];
  for (const write of writes) {
    if (write === "member") return "any";
    if (write === "unknown" || valueType(write, new Set()) === "any") {
      if (!primitive) return "any";
      continue;
    }
    known.push(write);
  }
  return withNull(unionTypes(known, uses));
}

/** Stands for a write whose result is a number: `$n++`, `$n -= 1`. */
const NUMBER: Expression = { kind: "Literal", value: 0 };

/** Array methods that change the array they are called on. */
const MUTATORS = new Set(["push", "unshift", "splice", "fill", "copyWithin"]);

/** `$x` / `x` for a direct reference to a binding, else `null`. */
function bindingKey(expr: Expression | undefined): string | null {
  if (expr?.kind === "StateRef") return `$${expr.name}`;
  if (expr?.kind === "Identifier") return expr.name;
  return null;
}

/** The binding a member chain starts from — `$cart` for `$cart.items[0].qty` — else `null`. */
function rootKey(expr: Expression | undefined): string | null {
  let node = expr;
  while (node?.kind === "Member" || node?.kind === "MethodCall") node = node.object;
  return bindingKey(node);
}

/** What `target <op>= value` leaves in a directly assigned binding. */
function compoundValue(operator: unknown, value: Expression | undefined): Written {
  if (value === undefined) return "unknown";
  // `=` and the logical forms store `value` itself (when they store anything).
  if (operator === "=" || operator === "??=" || operator === "||=" || operator === "&&=") return value;
  // `+=` concatenates or adds: a string operand makes a string, anything else is unknown.
  if (operator === "+=") return valueType(value, new Set()) === "string" ? value : "unknown";
  return NUMBER;
}

/**
 * Every value written to each binding anywhere in the module (`$x` / `x`),
 * initializers included — the widening input of {@link bindingType}. A write
 * is an assignment (`$x = v`, also in a lambda body), a compound assignment or
 * `++` / `--`, and anything that changes the value through a member chain that
 * starts at the binding: a member assignment or `delete`, an array mutator,
 * `Object.assign`. Writes inside component bodies count too, even where they
 * declare a local of the same name: that only widens. A write through another
 * name for the same object is not seen — `for (const t of $todos) t.done = x`
 * changes `$todos`'s rows in place.
 */
function assignedValues(program: Program): Map<string, Written[]> {
  const out = new Map<string, Written[]>();
  const record = (key: string | null, value: Written): void => {
    if (key === null) return;
    const list = out.get(key) ?? [];
    list.push(value);
    out.set(key, list);
  };
  walk(program, ({ node }) => {
    switch (node.kind) {
      case "Assignment":
        record(node.isState ? `$${node.identifier}` : node.identifier, node.expression);
        break;
      case "BuiltinCall": {
        const [target, value, op] = node.arguments;
        if (node.name === "__rui_assign__") {
          const direct = bindingKey(target);
          if (direct !== null) record(direct, compoundValue(op?.kind === "Literal" ? op.value : "=", value));
          else record(rootKey(target), "member");
        } else if (node.name === "__rui_prefix__" || node.name === "__rui_postfix__") {
          const direct = bindingKey(target);
          if (direct !== null) record(direct, NUMBER);
          else record(rootKey(target), "member");
        }
        break;
      }
      case "Unary":
        if (node.operator === "delete" && node.argument.kind === "Member") record(rootKey(node.argument), "member");
        break;
      case "MethodCall":
        if (MUTATORS.has(node.method)) record(rootKey(node.object), "member");
        if (node.object.kind === "Identifier" && node.object.name === "Object" && node.method === "assign") {
          record(rootKey(node.arguments[0]), "member");
        }
        break;
      default:
        break;
    }
  });
  return out;
}

/* -------------------------------------------------------------------------- */
/*  A project                                                                  */
/* -------------------------------------------------------------------------- */

/** A glob (`src/**\/*.aktion`) as an anchored RegExp over `/`-separated relative paths. */
function globToRegExp(glob: string): RegExp {
  let re = "";
  for (let i = 0; i < glob.length; i += 1) {
    const ch = glob[i]!;
    if (ch === "*") {
      if (glob[i + 1] === "*") {
        const slash = glob[i + 2] === "/";
        re += slash ? "(?:.*/)?" : ".*";
        i += slash ? 2 : 1;
      } else {
        re += "[^/]*";
      }
    } else if (ch === "?") {
      re += "[^/]";
    } else {
      re += /[\\^$.|+()[\]{}]/.test(ch) ? `\\${ch}` : ch;
    }
  }
  return new RegExp(`^${re}$`);
}

const toPosix = (p: string): string => p.split(sep).join("/");

function walkFiles(dir: string, skip: ReadonlySet<string>, out: string[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const name of entries) {
    const full = join(dir, name);
    if (skip.has(full)) continue;
    let stats;
    try {
      stats = statSync(full);
    } catch {
      continue;
    }
    if (stats.isDirectory()) {
      if (!SKIPPED_DIRECTORIES.has(name)) walkFiles(full, skip, out);
    } else if (stats.isFile()) {
      out.push(full);
    }
  }
}

/** True when `path` is `dir` or underneath it. */
function isInside(path: string, dir: string): boolean {
  const rel = relative(dir, path);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

interface Resolved {
  root: string;
  outDir: string;
  include: RegExp[];
  exclude: RegExp[];
  /** Alias targets and the directory each is mirrored into. */
  aliases: Array<{ target: string; mirror: string }>;
  write: boolean;
  warnings: string[];
}

function resolveOptions(options: AktionDeclarationsOptions): Resolved {
  const root = resolve(options.root ?? process.cwd());
  const outDir = resolve(root, options.outDir ?? DEFAULT_DECLARATIONS_DIR);
  const include = options.include ?? ["src/**/*.aktion"];
  const warnings: string[] = [];
  for (const glob of include) {
    if (glob.startsWith("../") || glob.startsWith("/") || isAbsolute(glob)) {
      warnings.push(
        `include "${glob}" matches nothing: globs are relative to the root (${root}) and cannot leave it. ` +
          "Declare a shared library through `alias` (aktion.config.json), or run aktion-dts with --root in the library.",
      );
    }
  }
  // Mirrored aliases need a directory of their own, even when each module's
  // declaration sits next to it.
  const mirrorRoot = outDir === root ? join(root, DEFAULT_DECLARATIONS_DIR) : outDir;
  const aliases: Resolved["aliases"] = [];
  for (const [prefix, target] of Object.entries(options.alias ?? {})) {
    const segments = prefix.replace(/\/+$/, "").split("/");
    if (isAbsolute(prefix) || segments.some((s) => s === "" || s === "." || s === "..")) {
      warnings.push(`alias "${prefix}" cannot be mirrored as a directory; its modules are not declared.`);
      continue;
    }
    aliases.push({ target: resolve(root, target), mirror: join(mirrorRoot, ...segments) });
  }
  return {
    root,
    outDir,
    include: include.map(globToRegExp),
    exclude: (options.exclude ?? []).map(globToRegExp),
    aliases,
    write: options.write !== false,
    warnings,
  };
}

const isModule = (file: string): boolean => /\.aktion$/i.test(file);
const excluded = (file: string, o: Resolved): boolean => o.exclude.some((re) => re.test(toPosix(relative(o.root, file))));

function isDeclared(file: string, o: Resolved): boolean {
  if (!isModule(file)) return false;
  const rel = toPosix(relative(o.root, file));
  if (rel.startsWith("..")) return false;
  return o.include.some((re) => re.test(rel)) && !excluded(file, o);
}

/** Every declaration a module gets: under `outDir` when `include` matches it, and in each alias mirror it sits in. */
function targetsOf(file: string, o: Resolved): string[] {
  const targets: string[] = [];
  if (isDeclared(file, o)) targets.push(join(o.outDir, declarationFileName(relative(o.root, file))));
  if (isModule(file) && !excluded(file, o)) {
    for (const { target, mirror } of o.aliases) {
      if (isInside(file, target)) targets.push(join(mirror, declarationFileName(relative(target, file))));
    }
  }
  return targets;
}

function emitOne(file: string, target: string, o: Resolved, result: AktionDeclarationsResult): void {
  const { text, errors } = aktionDeclarationText(readFileSync(file, "utf8"), toPosix(relative(o.root, file)));
  for (const e of errors) {
    if (!result.diagnostics.some((d) => d.path === file && d.line === e.line && d.column === e.column && d.message === e.message)) {
      result.diagnostics.push({ path: file, line: e.line, column: e.column, message: e.message });
    }
  }
  const current = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (current === text) {
    result.unchanged.push(target);
  } else {
    result.written.push(target);
    if (o.write) {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, text);
    }
  }
}

/** True when `file` is a declaration this module generated (its first line says so). */
function isGenerated(file: string): boolean {
  if (!file.endsWith(".d.aktion.ts")) return false;
  try {
    return readFileSync(file, "utf8").slice(0, DECLARATION_HEADER.length) === DECLARATION_HEADER;
  } catch {
    return false;
  }
}

/**
 * Write a `name.d.aktion.ts` declaration for every `.aktion` module under
 * `root` that `include` matches, and for every module under an `alias` target
 * — only where the text changed, so a watcher does not fire for nothing — and
 * remove generated declarations whose module is gone.
 */
export function emitAktionDeclarations(options: AktionDeclarationsOptions = {}): AktionDeclarationsResult {
  const o = resolveOptions(options);
  const result: AktionDeclarationsResult = { written: [], unchanged: [], removed: [], diagnostics: [], warnings: [...o.warnings] };
  const files: string[] = [];
  walkFiles(o.root, new Set([o.outDir]), files);
  for (const { target } of o.aliases) if (!isInside(target, o.root)) walkFiles(target, new Set(), files);
  const targets = new Set<string>();
  for (const file of [...new Set(files)].sort()) {
    for (const target of targetsOf(file, o)) {
      if (targets.has(target)) continue;
      targets.add(target);
      emitOne(file, target, o, result);
    }
  }

  // Stale declarations: generated by us (the header says so), module gone.
  const existing: string[] = [];
  walkFiles(o.outDir === o.root ? o.root : o.outDir, new Set(), existing);
  for (const file of existing) {
    if (targets.has(file) || !isGenerated(file)) continue;
    result.removed.push(file);
    if (o.write) rmSync(file, { force: true });
  }
  return result;
}

/**
 * Bring one module's declarations up to date — after an edit, or remove them
 * after a deletion. Used by the Vite plugin's dev server; a module neither
 * `include` nor an `alias` target covers is ignored.
 */
export function updateAktionDeclaration(file: string, options: AktionDeclarationsOptions = {}): AktionDeclarationsResult {
  const o = resolveOptions(options);
  const result: AktionDeclarationsResult = { written: [], unchanged: [], removed: [], diagnostics: [], warnings: [] };
  const absolute = resolve(file);
  for (const target of targetsOf(absolute, o)) {
    if (existsSync(absolute)) {
      emitOne(absolute, target, o, result);
    } else if (existsSync(target)) {
      result.removed.push(target);
      if (o.write) rmSync(target, { force: true });
    }
  }
  return result;
}
