/**
 * Declarations for `.aktion` modules (guide §7.10, Phase 3.4):
 * `emitAktionDeclarations`, the plugin's `dts` option and the `aktion-dts`
 * bin. The end-to-end check is a real `tsc` run: the generated sidecars make a
 * `.aktion.ts` file that imports from `.aktion` modules type-check, and a wrong
 * arity fails with TS2554.
 */

import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  aktionDeclarationText,
  declarationFileName,
  emitAktionDeclarations,
  updateAktionDeclaration,
  aktionPlugin,
} from "../src/plugin/index.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tscBin = join(repoRoot, "node_modules/typescript/bin/tsc");
const binScript = join(repoRoot, "bin/aktion-dts.mjs");

const TODO_ROW = [
  "export $count = 0",
  'export accent = "teal"',
  "export let limit = 5",
  "export function TodoRow(todo, { dense }) {",
  "  return Text(todo.title)",
  "}",
  "export function track(name, ...tags) {",
  "  $count = $count + 1",
  "}",
  "export function $useToggle(initial) {",
  "  return initial",
  "}",
  "function Private() { return null }",
  "",
].join("\n");

let dir = "";
const put = (rel: string, text: string): string => {
  const path = join(dir, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
  return path;
};

beforeAll(() => {
  dir = mkdtempSync(join(tmpdir(), "aktion-dts-"));
});
afterAll(() => rmSync(dir, { recursive: true, force: true }));

describe("aktionDeclarationText", () => {
  it("declares each kind of export as §7.10 specifies", () => {
    expect(aktionDeclarationText(TODO_ROW, "src/todo-row.aktion").text).toBe(
      [
        "// Generated by aktion-dts from src/todo-row.aktion — do not edit.",
        'import type { AktionNode, CompiledProgram } from "aktion-runtime/dsl";',
        "",
        "export declare let $count: number;",
        "export declare const accent: string;",
        "export declare let limit: number;",
        "export declare function TodoRow(todo?: any, p1?: any, ...rest: any[]): AktionNode;",
        "export declare function track(name?: any, ...tags: any[]): any;",
        "export declare function $useToggle(...args: any[]): any;",
        "",
        "declare const compiled: CompiledProgram;",
        "export default compiled;",
        "",
      ].join("\n"),
    );
  });

  it("declares a module without exports as its compiled program only", () => {
    const { text, errors } = aktionDeclarationText('$app(Text("x"))', "app.aktion");
    expect(errors).toEqual([]);
    expect(text).toContain('import type { CompiledProgram } from "aktion-runtime/dsl";');
    expect(text).toContain("export default compiled;");
    expect(text).not.toContain("AktionNode");
  });

  it("reports parse errors and declares what parsed", () => {
    const { text, errors } = aktionDeclarationText("export function ok() { return 1 }\nexport function bad( {", "x.aktion");
    expect(errors.length).toBeGreaterThan(0);
    expect(text).toContain("export declare function ok(): any;");
  });

  it("names the sidecar TypeScript looks up for the module", () => {
    expect(declarationFileName("src/components/todo-row.aktion")).toBe("src/components/todo-row.d.aktion.ts");
  });
});

describe("emitAktionDeclarations", () => {
  it("writes mirrored declarations into `.aktion-types`, only when they change, and removes orphans", () => {
    const root = join(dir, "emit");
    mkdirSync(root);
    const prev = dir;
    dir = root;
    try {
      put("src/todo-row.aktion", TODO_ROW);
      put("src/nested/panel.aktion", 'export function Panel() { return Text("p") }');
      put("src/skip.aktion.ts", "export const n = 1");
      put("lib/outside.aktion", "export x = 1");
      put("node_modules/pkg/dep.aktion", "export y = 1");

      const first = emitAktionDeclarations({ root });
      expect(first.written.map((p) => p.slice(root.length + 1)).sort()).toEqual([
        ".aktion-types/src/nested/panel.d.aktion.ts",
        ".aktion-types/src/todo-row.d.aktion.ts",
      ]);
      expect(readFileSync(join(root, ".aktion-types/src/todo-row.d.aktion.ts"), "utf8")).toContain("TodoRow");

      const second = emitAktionDeclarations({ root });
      expect(second.written).toEqual([]);
      expect(second.unchanged).toHaveLength(2);

      rmSync(join(root, "src/nested/panel.aktion"));
      const third = emitAktionDeclarations({ root });
      expect(third.removed.map((p) => p.slice(root.length + 1))).toEqual([".aktion-types/src/nested/panel.d.aktion.ts"]);
      expect(existsSync(join(root, ".aktion-types/src/nested/panel.d.aktion.ts"))).toBe(false);
    } finally {
      dir = prev;
    }
  });

  it("honours include, exclude, an in-tree outDir and `write: false`", () => {
    const root = join(dir, "options");
    mkdirSync(root);
    const prev = dir;
    dir = root;
    try {
      put("app/a.aktion", "export a = 1");
      put("app/b.aktion", "export b = 1");
      const dry = emitAktionDeclarations({ root, include: ["app/**/*.aktion"], exclude: ["app/b.aktion"], outDir: ".", write: false });
      expect(dry.written.map((p) => p.slice(root.length + 1))).toEqual(["app/a.d.aktion.ts"]);
      expect(existsSync(join(root, "app/a.d.aktion.ts"))).toBe(false);
      emitAktionDeclarations({ root, include: ["app/**/*.aktion"], outDir: "." });
      expect(existsSync(join(root, "app/a.d.aktion.ts"))).toBe(true);
      expect(existsSync(join(root, "app/b.d.aktion.ts"))).toBe(true);
    } finally {
      dir = prev;
    }
  });

  it("updateAktionDeclaration refreshes one module and removes the declaration of a deleted one", () => {
    const root = join(dir, "update");
    mkdirSync(root);
    const prev = dir;
    dir = root;
    try {
      const file = put("src/x.aktion", "export function a() {}");
      expect(updateAktionDeclaration(file, { root }).written).toHaveLength(1);
      writeFileSync(file, "export function a(one, two) {}");
      updateAktionDeclaration(file, { root });
      expect(readFileSync(join(root, ".aktion-types/src/x.d.aktion.ts"), "utf8")).toContain("a(one?: any, two?: any)");
      rmSync(file);
      expect(updateAktionDeclaration(file, { root }).removed).toHaveLength(1);
      expect(updateAktionDeclaration(join(root, "elsewhere/y.aktion"), { root }).written).toEqual([]);
    } finally {
      dir = prev;
    }
  });
});

describe("the plugin's `dts` option", () => {
  it("emits on buildStart", async () => {
    const root = join(dir, "plugin");
    mkdirSync(join(root, "src"), { recursive: true });
    writeFileSync(join(root, "src/card.aktion"), "export function Card(title) { return Text(title) }");
    const plugin = aktionPlugin({ dts: true }) as unknown as {
      configResolved: (c: { command: string; root: string }) => void;
      buildStart: (this: unknown) => Promise<void>;
    };
    plugin.configResolved({ command: "build", root });
    await plugin.buildStart.call({ warn() {} });
    expect(readFileSync(join(root, ".aktion-types/src/card.d.aktion.ts"), "utf8")).toContain(
      "export declare function Card(title?: any, ...rest: any[]): AktionNode;",
    );
  });
});

describe("type-checking `.aktion.ts` against generated declarations", () => {
  let project = "";
  const tsc = (config: string): { code: number; output: string } => {
    const run = spawnSync(process.execPath, [tscBin, "-p", config], { encoding: "utf8" });
    return { code: run.status ?? 1, output: `${run.stdout}${run.stderr}` };
  };

  beforeAll(() => {
    project = join(dir, "tsc");
    for (const [rel, text] of Object.entries({
      "src/todo-row.aktion": TODO_ROW,
      "src/app.aktion": 'import { TodoRow } from "./todo-row.aktion"\n$app(TodoRow({ title: "x" }))',
      "src/main.aktion.ts": [
        'import app from "./app.aktion"',
        'import { TodoRow, track, $count, accent } from "./todo-row.aktion"',
        "export const view = TodoRow({ title: \"a\" }, { dense: true })",
        'track("x", "y", "z")',
        "export const n: number = $count + accent.length",
        "export const program = app.program",
      ].join("\n"),
      "src/bad.aktion.ts": ['import { $useToggle } from "./todo-row.aktion"', 'import { track } from "./missing-arity.aktion"', "$useToggle(1, 2)", "track(1, 2, 3)"].join("\n"),
      "src/missing-arity.aktion": "export function track(name) { return name }",
    })) {
      mkdirSync(dirname(join(project, rel)), { recursive: true });
      writeFileSync(join(project, rel), text);
    }
    // `aktion-runtime/dsl` resolves to the committed declarations, beside a
    // stand-in for the runtime module they import `CompiledProgram` from.
    mkdirSync(join(project, "stage/dsl"), { recursive: true });
    mkdirSync(join(project, "stage/compiler"), { recursive: true });
    writeFileSync(join(project, "stage/dsl/index.d.ts"), readFileSync(join(repoRoot, "src/dsl/index.d.ts"), "utf8"));
    writeFileSync(
      join(project, "stage/compiler/runtime.d.ts"),
      "export interface CompiledProgram { readonly __aktionCompiled: 1; readonly program: unknown; readonly source: string; readonly path: string; readonly sourcesContent?: readonly string[] }\n",
    );
    const config = (files: string[]) => ({
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "Bundler",
        lib: ["ES2022", "DOM"],
        strict: true,
        noEmit: true,
        skipLibCheck: true,
        types: [],
        allowArbitraryExtensions: true,
        rootDirs: ["src", ".aktion-types/src"],
        paths: { "aktion-runtime/dsl": ["./stage/dsl/index.d.ts"] },
      },
      files,
    });
    writeFileSync(join(project, "tsconfig.json"), JSON.stringify(config(["src/main.aktion.ts"]), null, 2));
    writeFileSync(join(project, "tsconfig.bad.json"), JSON.stringify(config(["src/bad.aktion.ts"]), null, 2));
  });

  it("fails before the declarations exist (TS2307 / TS2614)", () => {
    const run = tsc(join(project, "tsconfig.json"));
    expect(run.code).not.toBe(0);
    expect(run.output).toMatch(/TS2307|TS2614/);
  });

  it("type-checks once they are generated", () => {
    emitAktionDeclarations({ root: project });
    const run = tsc(join(project, "tsconfig.json"));
    expect(run.output).toBe("");
    expect(run.code).toBe(0);
  }, 60_000);

  it("catches a wrong arity (TS2554)", () => {
    emitAktionDeclarations({ root: project });
    const run = tsc(join(project, "tsconfig.bad.json"));
    expect(run.code).not.toBe(0);
    expect(run.output).toMatch(/bad\.aktion\.ts\(4,\d+\): error TS2554: Expected 0-1 arguments, but got 3\./);
    // A hook takes anything.
    expect(run.output).not.toMatch(/bad\.aktion\.ts\(3,/);
  }, 60_000);
});

describe("the aktion-dts bin", () => {
  beforeAll(() => {
    if (existsSync(join(repoRoot, "dist/plugin.js"))) return;
    // Build into a scratch dir and MOVE the result in, `.js` last, as
    // `tests/validate-tools.test.ts` does: sibling workers import
    // `dist/plugin.js` as soon as it exists, and rollup writes it in place.
    const dist = join(repoRoot, "dist");
    mkdirSync(dist, { recursive: true });
    const stage = mkdtempSync(join(dist, "test-build-"));
    try {
      execFileSync(
        process.execPath,
        [join(repoRoot, "node_modules/vite/bin/vite.js"), "build", "--config", "vite.plugin.config.ts", "--outDir", stage],
        { cwd: repoRoot, stdio: "pipe" },
      );
      const produced = readdirSync(stage);
      const isModule = (f: string): boolean => f.endsWith(".js") || f.endsWith(".cjs");
      for (const name of [...produced.filter((f) => !isModule(f)), ...produced.filter(isModule)]) {
        renameSync(join(stage, name), join(dist, name));
      }
    } finally {
      rmSync(stage, { recursive: true, force: true });
    }
  }, 120_000);

  it("writes declarations, and `--check` fails until they are current", () => {
    const root = join(dir, "bin");
    mkdirSync(join(root, "src"), { recursive: true });
    writeFileSync(join(root, "src/a.aktion"), "export function A() { return null }");
    const run = (args: string[]) => spawnSync(process.execPath, [binScript, ...args], { cwd: root, encoding: "utf8" });

    const stale = run(["--check"]);
    expect(stale.status).toBe(1);
    expect(stale.stderr).toContain(".aktion-types/src/a.d.aktion.ts");

    const write = run([]);
    expect(write.status).toBe(0);
    expect(write.stdout).toContain("1 written, 0 unchanged, 0 removed");

    const fresh = run(["--check"]);
    expect(fresh.status).toBe(0);
    expect(fresh.stdout).toContain("1 declaration(s) up to date");

    expect(run(["--bogus"]).status).toBe(2);
  });
});
