/**
 * The VS Code extension's *prose* is the one place editor artifacts are allowed
 * to state language facts as literals — a marketplace `description` cannot call
 * `defaultLibrary.components.length`. Those literals rot silently: the shipped
 * description claimed a "275-component library" for two releases after the
 * library had grown past it, and nothing failed.
 *
 * So the numbers are asserted here instead. A component, builtin, snippet or
 * theme change now breaks this test rather than shipping a wrong blurb.
 * See `.cursor/rules/editor-tooling-sync.mdc`.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { defaultLibrary } from "../src/library/index.js";
import { builtinCatalog } from "../src/language/builtins.js";
import { namespaceCatalog, factoryResourceCatalog } from "../src/language/namespaces.js";
import { getSnippets } from "../src/language/snippets.js";
import { builtInThemes } from "../src/theme/index.js";
import { semanticTokenTypes, semanticTokenModifiers } from "../src/tooling/semantic-tokens.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const readJson = (path: string): Record<string, any> =>
  JSON.parse(readFileSync(resolve(root, path), "utf8"));
const readText = (path: string): string => readFileSync(resolve(root, path), "utf8");

const rootPkg = readJson("package.json");
const extensionPkg = readJson("editors/vscode/package.json");
const extensionReadme = readText("editors/vscode/README.md");

const componentCount = defaultLibrary.components.length;
const groupCount = (defaultLibrary.componentGroups ?? []).length;
const namespaceMemberCount = namespaceCatalog.reduce((n, ns) => n + ns.members.length, 0);
const themeNames = Object.keys(builtInThemes);

describe("VS Code extension metadata", () => {
  it("the marketplace description states the real component count", () => {
    expect(extensionPkg.description).toContain(`${componentCount}-component library`);
  });

  it("the marketplace description states the real builtin and theme counts", () => {
    expect(extensionPkg.description).toContain(`all ${builtinCatalog.length} $-builtins`);
    expect(extensionPkg.description).toContain(`${themeNames.length} built-in themes`);
  });

  it("every $-builtin the description names exists, and none is missing", () => {
    const claimed = new Set(extensionPkg.description.match(/\$[a-z][A-Za-z0-9]*/g) ?? []);
    const real = new Set(builtinCatalog.map((b) => b.sigil));
    const invented = [...claimed].filter((name) => !real.has(name));
    const unmentioned = [...real].filter((name) => !claimed.has(name));
    expect(invented, "description names builtins that do not exist").toEqual([]);
    expect(unmentioned, 'description says "all N $-builtins" but omits these').toEqual([]);
  });

  it("the README's at-a-glance line matches the runtime", () => {
    // One line, six figures — the numbers a user reads before installing.
    expect(extensionReadme).toContain(`${componentCount} components across ${groupCount} groups`);
    expect(extensionReadme).toContain(`${builtinCatalog.length} \`$\`-builtins`);
    expect(extensionReadme).toContain(`${namespaceCatalog.length} namespaces`);
    expect(extensionReadme).toContain(`(${namespaceMemberCount} members)`);
    expect(extensionReadme).toContain(`${factoryResourceCatalog.length} factory resource bags`);
    expect(extensionReadme).toContain(`${getSnippets().length} snippets`);
    expect(extensionReadme).toContain(`${themeNames.length} built-in themes`);
    for (const theme of themeNames) expect(extensionReadme).toContain(`\`${theme}\``);
  });

  it("the extension version tracks the runtime version exactly", () => {
    // The language surface is INLINED into dist/extension.js, so a published
    // extension serves the runtime it was built against — see
    // editors/vscode/docs/README.md on version lockstep.
    expect(extensionPkg.version).toBe(rootPkg.version);
    expect(extensionPkg.devDependencies["aktion-runtime"]).toBe(`^${rootPkg.version}`);
  });

  it("the generated grammar's builtin alternation covers every builtin", () => {
    const grammar = readJson("editors/vscode/syntaxes/aktion.tmLanguage.json");
    const match: string = grammar.repository["aktion-builtin"].match;
    const alternation = /^\\\$\(\?:(.+)\)\\b$/.exec(match);
    expect(alternation, `unexpected builtin pattern: ${match}`).not.toBeNull();
    expect(alternation![1].split("|").sort()).toEqual(
      builtinCatalog.map((b) => b.name).sort(),
    );
  });

  it("the generated snippet file carries every snippet", () => {
    // Generated by editors/vscode/scripts/gen-snippets.mjs during its build; skip
    // when that build has not run in this checkout rather than failing the suite.
    let snippetFile: Record<string, any>;
    try {
      snippetFile = readJson("editors/vscode/snippets/aktion.code-snippets");
    } catch {
      return;
    }
    expect(Object.keys(snippetFile).sort()).toEqual(getSnippets().map((s) => s.name).sort());
  });

  it("semanticTokenScopes maps every token type the service can emit", () => {
    const scopes: Record<string, string[]> = extensionPkg.contributes.semanticTokenScopes[0].scopes;
    for (const type of semanticTokenTypes) {
      expect(Object.keys(scopes), `missing scope mapping for "${type}"`).toContain(type);
    }
    // Modifier-qualified entries are optional per type, but any that IS declared
    // must name a modifier the service actually produces.
    const qualified = Object.keys(scopes).filter((key) => key.includes("."));
    for (const key of qualified) {
      const [type, modifier] = key.split(".");
      expect(semanticTokenTypes as readonly string[]).toContain(type);
      expect(semanticTokenModifiers as readonly string[]).toContain(modifier);
    }
  });

  it("every contributed command is registered by the extension source", () => {
    const source = readText("editors/vscode/src/commands.ts");
    for (const command of extensionPkg.contributes.commands as Array<{ command: string }>) {
      expect(source, `${command.command} is contributed but never registered`).toContain(
        `"${command.command}"`,
      );
    }
  });

  it("every setting the extension reads is contributed", () => {
    const declared = Object.keys(extensionPkg.contributes.configuration.properties);
    const source = readText("editors/vscode/src/extension.ts");
    // `settings()` reads them relative to the "aktion" section.
    const read = [...source.matchAll(/get<[^>]+>\("([^"]+)"/g)].map((m) => `aktion.${m[1]}`);
    expect(read.length).toBeGreaterThan(0);
    for (const key of read) expect(declared).toContain(key);
  });
});
