#!/usr/bin/env node
/**
 * Generate `syntaxes/aktion.tmLanguage.json` from the language surface so the
 * TextMate overlays stay in lockstep with the runtime — the list of
 * `$`-builtins and reserved handles is never hand-maintained here.
 *
 * `.aktion` is a strict subset of TypeScript, so the grammar embeds the full
 * `source.ts` grammar and only adds a few Aktion-specific overlays:
 *   - `$`-prefixed builtins (`$state`, `$effect`, `$http`, `$util`, …)
 *   - reactive `$state` references
 *   - PascalCase component calls
 *   - reserved handles (`route`, `aktion`)
 *
 * Resolves the language surface from the repo's built `dist/language.js`, or
 * falls back to the TypeScript source via a tiny esbuild transform.
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");

async function bundleFromSource() {
  const { build } = await import("esbuild");
  const out = resolve(here, ".gen-grammar.tmp.mjs");
  await build({
    entryPoints: [resolve(repoRoot, "src/language-api.ts")],
    outfile: out,
    bundle: true,
    format: "esm",
    platform: "node",
    logLevel: "silent",
  });
  return await import(`${pathToFileURL(out).href}?t=${Date.now()}`);
}

async function loadSurface() {
  const built = resolve(repoRoot, "dist/language.js");
  if (existsSync(built)) {
    const mod = await import(pathToFileURL(built).href);
    // A stale `dist/language.js` (predating the builtin catalog) lacks the
    // export — fall back to bundling the TS source so the build still works.
    if (Array.isArray(mod.builtinCatalog)) return mod;
  }
  return await bundleFromSource();
}

const surface = await loadSurface();
const builtinNames = surface.builtinCatalog.map((b) => b.name).join("|");

const grammar = {
  $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  name: "Aktion",
  scopeName: "source.aktion",
  comment:
    "GENERATED by scripts/gen-grammar.mjs — do not edit by hand. Aktion is a strict subset of TypeScript, so we highlight it with the full TypeScript grammar (source.ts) and add Aktion-specific overlays.",
  patterns: [
    { include: "#aktion-builtin" },
    { include: "#aktion-state" },
    { include: "#aktion-component-call" },
    { include: "#aktion-handle" },
    { include: "source.ts" },
  ],
  repository: {
    "aktion-builtin": {
      comment:
        "Runtime $-builtins (hooks, factories, namespaces) — kept in sync with src/language/builtins.ts.",
      match: `\\$(?:${builtinNames})\\b`,
      name: "support.function.builtin.aktion",
    },
    "aktion-state": {
      comment:
        "Reactive state references like $count, $user — the `$` sigil is what makes a binding reactive.",
      match: "\\$[A-Za-z_][A-Za-z0-9_]*",
      name: "variable.language.aktion.state",
    },
    "aktion-component-call": {
      comment: "PascalCase component invocations like Card( / Button( get a type-like color.",
      match: "\\b([A-Z][A-Za-z0-9_]*)(?=\\s*\\()",
      captures: { 1: { name: "entity.name.type.component.aktion" } },
    },
    "aktion-handle": {
      comment: "Reserved runtime handles surfaced as identifiers (route, aktion).",
      match: "\\b(route|aktion)\\b",
      name: "support.variable.aktion",
    },
  },
};

const target = resolve(here, "../syntaxes/aktion.tmLanguage.json");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, `${JSON.stringify(grammar, null, 2)}\n`, "utf8");

// eslint-disable-next-line no-console
console.log(`Wrote TextMate grammar (${surface.builtinCatalog.length} builtins) to ${target}`);

/* -------------------------------------------------------------------------- */
/*  HTML injection grammar                                                    */
/*                                                                            */
/*  Aktion programs can also be embedded directly in a plain HTML page inside */
/*  an `<aktion-app>` … `</aktion-app>` element. This injection grammar tells */
/*  the editor to highlight that inner content with the full `source.aktion`  */
/*  grammar — the same colours `.aktion` files get — so the embedded program  */
/*  reads identically whether it lives in a file or a tag.                    */
/*                                                                            */
/*  The opening-tag match deliberately requires a non-self-closing `>` (the   */
/*  `(?<!/)` lookbehind) so a self-closing `<aktion-app/>` is left alone and  */
/*  the rest of the document is never mis-scanned as Aktion source.           */
/* -------------------------------------------------------------------------- */

const injectionGrammar = {
  $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  name: "Aktion (embedded in HTML)",
  scopeName: "aktion-app.injection.html",
  comment:
    "GENERATED by scripts/gen-grammar.mjs — do not edit by hand. Injects source.aktion into the body of an <aktion-app> element in HTML files.",
  injectionSelector: "L:text.html -comment -string",
  patterns: [{ include: "#aktion-app-embedded" }],
  repository: {
    "aktion-app-embedded": {
      comment:
        "Match the full <aktion-app …> opening tag (non-self-closing) and highlight everything up to </aktion-app> as Aktion source.",
      begin: "(?i)(<)(aktion-app)\\b([^>]*?)(?<!/)(>)",
      beginCaptures: {
        1: { name: "punctuation.definition.tag.begin.html" },
        2: { name: "entity.name.tag.html" },
        3: { patterns: [{ include: "#tag-attributes" }] },
        4: { name: "punctuation.definition.tag.end.html" },
      },
      end: "(?i)(</)(aktion-app)\\s*(>)",
      endCaptures: {
        1: { name: "punctuation.definition.tag.begin.html" },
        2: { name: "entity.name.tag.html" },
        3: { name: "punctuation.definition.tag.end.html" },
      },
      contentName: "meta.embedded.block.aktion",
      patterns: [{ include: "source.aktion" }],
    },
    "tag-attributes": {
      comment: "Minimal, self-contained highlighting for the opening tag's attributes.",
      patterns: [
        { begin: '"', end: '"', name: "string.quoted.double.html" },
        { begin: "'", end: "'", name: "string.quoted.single.html" },
        { match: "=", name: "punctuation.separator.key-value.html" },
        { match: "[a-zA-Z_:][\\w:.-]*", name: "entity.other.attribute-name.html" },
      ],
    },
  },
};

const injectionTarget = resolve(here, "../syntaxes/aktion-html-injection.tmLanguage.json");
writeFileSync(injectionTarget, `${JSON.stringify(injectionGrammar, null, 2)}\n`, "utf8");

// eslint-disable-next-line no-console
console.log(`Wrote HTML injection grammar to ${injectionTarget}`);
