#!/usr/bin/env node
/**
 * Generate the machine-derived half of the Aktion agent skill.
 *
 * `skills/aktion/SKILL.md` and the two prose references (`patterns.md`,
 * `gotchas.md`) are HAND-WRITTEN — they carry judgement, and no generator can
 * invent them. Everything that is a projection of the runtime is written here:
 *
 *   references/components/index.md      the catalogue index (group → names)
 *   references/components/<group>.md    one file per component group
 *   references/builtins.md              every $-builtin + its config keys
 *   references/namespaces.md            namespace members + resource bags
 *   references/themes.md                built-in themes + every token
 *
 * Why generate instead of hand-writing: the predecessor of this skill
 * (`coding-gen-skill.md`) was a single 4,000-line hand-maintained file, and a
 * hand-maintained component reference is guaranteed to drift — a skill that
 * names a component that no longer exists makes an agent produce broken code,
 * silently. `tests/skill-artifacts.test.ts` fails if these files are stale, so
 * drift is a red test rather than a bad generation months later.
 *
 * Runs as part of `npm run build` (see package.json), after the language bundle
 * exists. Reads ONLY `dist/language.js` — the DOM-free surface — so no DOM shim
 * is needed here.
 */

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const bundlePath = resolve(repoRoot, "dist/language.js");
const skillDir = resolve(repoRoot, "skills/aktion");
const referencesDir = resolve(skillDir, "references");
const componentsDir = resolve(referencesDir, "components");

const GENERATED_BANNER = (what) =>
  `<!--\n  GENERATED by scripts/emit-skill.mjs — do not edit by hand.\n  Source of truth: ${what}\n  Regenerate with \`npm run build:skill\` (or \`npm run build\`).\n-->\n`;

/* -------------------------------------------------------------------------- */
/*  Helpers                                                                   */
/* -------------------------------------------------------------------------- */

const slug = (name) =>
  name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

/** Escape the `|` characters that would otherwise break a markdown table row. */
const cell = (text) => String(text ?? "").replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();

/**
 * Render a component's props as a markdown table. Positional props are the ones
 * an author passes bare, in order, so the order here is load-bearing — it IS the
 * call signature.
 */
function propTable(params) {
  if (params.length === 0) return "_No props._\n";
  const rows = params.map((p) => {
    const type = p.enumValues?.length
      ? p.enumValues.map((v) => `\`"${v}"\``).join(" \\| ")
      : `\`${p.type}\``;
    return `| \`${p.name}\` | ${type} | ${p.required ? "**yes**" : "no"} | ${cell(p.description ?? "")} |`;
  });
  return ["| prop | type / values | required | notes |", "| --- | --- | --- | --- |", ...rows].join(
    "\n",
  );
}

/* -------------------------------------------------------------------------- */
/*  Components                                                                */
/* -------------------------------------------------------------------------- */

async function writeComponents(surface) {
  const catalog = surface.getComponentCatalog();
  const groups = surface.defaultLibrary.componentGroups;
  const byName = new Map(catalog.map((c) => [c.name, c]));

  // A component with no group would be invisible in a per-group reference —
  // exactly the failure mode `tests/component-groups-complete.test.ts` guards in
  // the prompt. Fail loudly rather than silently dropping it from the skill.
  const grouped = new Set(groups.flatMap((g) => g.components));
  const orphans = catalog.filter((c) => !grouped.has(c.name)).map((c) => c.name);
  if (orphans.length > 0) {
    throw new Error(
      `These components are in the library but in no componentGroup, so they would be missing ` +
        `from the skill reference: ${orphans.join(", ")}. Add them to a group in src/library/index.ts.`,
    );
  }

  await rm(componentsDir, { recursive: true, force: true });
  await mkdir(componentsDir, { recursive: true });

  const indexLines = [
    GENERATED_BANNER("`getComponentCatalog()` + `defaultLibrary.componentGroups`"),
    "# Component catalogue",
    "",
    `${catalog.length} components in ${groups.length} groups. **Only these names exist** — a`,
    "PascalCase call that is not in this list and that you did not declare yourself is an",
    "error the runtime will not render.",
    "",
    "Open the group file for full signatures, prop tables, and the authoring notes that say",
    "*when* to reach for each component.",
    "",
    "| Group | Components | Reference |",
    "| --- | --: | --- |",
  ];

  for (const group of groups) {
    const file = `${slug(group.name)}.md`;
    indexLines.push(
      `| ${group.name} | ${group.components.length} | [\`components/${file}\`](./${file}) |`,
    );
  }

  indexLines.push("", "## Every component, by group", "");
  for (const group of groups) {
    indexLines.push(`### ${group.name}`, "");
    indexLines.push(
      group.components
        .map((name) => {
          const entry = byName.get(name);
          return entry ? `\`${entry.signature}\`` : `\`${name}\``;
        })
        .join(" · "),
      "",
    );
  }

  await writeFile(resolve(componentsDir, "index.md"), `${indexLines.join("\n")}\n`, "utf8");

  for (const group of groups) {
    const lines = [
      GENERATED_BANNER("`getComponentCatalog()` + `defaultLibrary.componentGroups`"),
      `# ${group.name}`,
      "",
      `${group.components.length} components. [← back to the catalogue index](./index.md)`,
      "",
    ];

    if (group.notes?.length) {
      lines.push(
        "## When to use what",
        "",
        "These are the library's own authoring notes — they encode the intended choice",
        "between similar components, which the prop tables below cannot express.",
        "",
        ...group.notes.map((n) => n.replace(/^-\s*/, "- ")),
        "",
      );
    }

    lines.push("## Reference", "");
    for (const name of group.components) {
      const entry = byName.get(name);
      if (!entry) continue; // guarded above; belt-and-braces
      lines.push(`### ${entry.name}`, "", `\`\`\`\n${entry.signature}\n\`\`\``, "");
      if (entry.description) lines.push(entry.description, "");
      lines.push(propTable(entry.params), "");
    }

    await writeFile(resolve(componentsDir, `${slug(group.name)}.md`), `${lines.join("\n")}\n`, "utf8");
  }

  return { componentCount: catalog.length, groupCount: groups.length };
}

/* -------------------------------------------------------------------------- */
/*  Builtins                                                                  */
/* -------------------------------------------------------------------------- */

const CATEGORY_ORDER = ["hook", "effect", "data", "app", "routing", "theme", "event", "namespace"];
const CATEGORY_BLURB = {
  hook: "Per-instance state, mirroring React's `useState` / `useMemo` / `useRef` / `useReducer` / `useId`.",
  effect: "Side effects, transactions, global stores, and managed forms.",
  data: "Data resources. Each returns a **reactive bag** — see `namespaces.md` for its members.",
  app: "Application-level declarations.",
  routing: "Client-side routing.",
  theme: "Design tokens.",
  event: "Escaping to the host page.",
  namespace: "Reserved namespaces — call members on them, never call the namespace itself.",
};

async function writeBuiltins(surface) {
  const { builtinCatalog, findBuiltinConfig } = surface;
  const lines = [
    GENERATED_BANNER("`builtinCatalog` + `findBuiltinConfig()`"),
    "# `$`-builtins",
    "",
    `All ${builtinCatalog.length} builtins the runtime dispatches. A \`$\`-prefixed callee that`,
    "is not in this list is **not** a builtin — it is either one of your own hooks",
    "(`function $useThing()`) or a mistake.",
    "",
    "The `$` sigil is what makes a binding reactive. `$name = value` declares a reactive atom;",
    "reassigning it re-renders the parts of the tree that read it.",
    "",
  ];

  const byCategory = new Map();
  for (const b of builtinCatalog) {
    if (!byCategory.has(b.category)) byCategory.set(b.category, []);
    byCategory.get(b.category).push(b);
  }
  const categories = [
    ...CATEGORY_ORDER.filter((c) => byCategory.has(c)),
    ...[...byCategory.keys()].filter((c) => !CATEGORY_ORDER.includes(c)),
  ];

  lines.push("## At a glance", "", "| builtin | category | signature |", "| --- | --- | --- |");
  for (const category of categories) {
    for (const b of byCategory.get(category)) {
      lines.push(`| \`${b.sigil}\` | ${category} | \`${cell(b.signature)}\` |`);
    }
  }
  lines.push("");

  for (const category of categories) {
    lines.push(`## ${category}`, "");
    if (CATEGORY_BLURB[category]) lines.push(CATEGORY_BLURB[category], "");
    for (const b of byCategory.get(category)) {
      lines.push(`### \`${b.sigil}\``, "", `\`\`\`\n${b.signature}\n\`\`\``, "");
      if (b.summary) lines.push(b.summary, "");

      const config = findBuiltinConfig(b.name);
      if (config?.length) {
        lines.push(
          `**Config keys** — the only keys \`${b.sigil}({ … })\` accepts:`,
          "",
          "| key | type | notes |",
          "| --- | --- | --- |",
          ...config.map((k) => `| \`${k.name}\` | \`${cell(k.type)}\` | ${cell(k.summary ?? "")} |`),
          "",
        );
      }
    }
  }

  await writeFile(resolve(referencesDir, "builtins.md"), `${lines.join("\n")}\n`, "utf8");
  return { builtinCount: builtinCatalog.length };
}

/* -------------------------------------------------------------------------- */
/*  Namespaces + reactive resource bags                                       */
/* -------------------------------------------------------------------------- */

function memberTable(members) {
  return [
    "| member | kind | signature | notes |",
    "| --- | --- | --- | --- |",
    ...members.map(
      (m) =>
        `| \`${m.name}\` | ${m.kind} | \`${cell(m.signature)}\` | ${cell(m.summary ?? "")} |`,
    ),
  ].join("\n");
}

async function writeNamespaces(surface) {
  const { namespaceCatalog, factoryResourceCatalog, routeMembers, i18nResultMembers } = surface;
  const memberTotal = namespaceCatalog.reduce((n, ns) => n + ns.members.length, 0);

  const lines = [
    GENERATED_BANNER("`namespaceCatalog`, `factoryResourceCatalog`, `routeMembers`, `i18nResultMembers`"),
    "# Namespaces & reactive resource bags",
    "",
    `${memberTotal} members across ${namespaceCatalog.length} namespaces, plus the bag each`,
    `data builtin returns (${factoryResourceCatalog.length} of them).`,
    "",
    "**This is the list to check before inventing a helper.** Most of what a program needs —",
    "formatting, dates, collections, validation, storage, clipboard, geolocation, workers — is",
    "already a `$util.*` or `$storage.*` member. Reaching for raw JavaScript when a member",
    "exists is the most common way an Aktion program ends up longer and less reliable than it",
    "needs to be.",
    "",
    "## Namespaces",
    "",
  ];

  for (const ns of namespaceCatalog) {
    lines.push(`### \`$${ns.name}\``, "");
    if (ns.summary) lines.push(ns.summary, "");
    lines.push(`${ns.members.length} members.`, "", memberTable(ns.members), "");
  }

  lines.push(
    "## Reactive resource bags",
    "",
    "A data builtin returns a bag, not a value: `$todos = $http({ url })` makes `$todos.data`,",
    "`$todos.loading`, `$todos.error`, and `$todos.refetch()` available and reactive. Read the",
    "bag's members — never treat the binding itself as the payload.",
    "",
  );
  for (const resource of factoryResourceCatalog) {
    lines.push(`### \`$${resource.factory}({ … })\` →`, "");
    if (resource.summary) lines.push(resource.summary, "");
    lines.push(memberTable(resource.members), "");
  }

  lines.push(
    "## The `route` handle",
    "",
    "Always in scope; reactive. Read the current location, navigate imperatively.",
    "",
    memberTable(routeMembers),
    "",
    "## What `$i18n({ … })` destructures to",
    "",
    memberTable(i18nResultMembers),
    "",
  );

  await writeFile(resolve(referencesDir, "namespaces.md"), `${lines.join("\n")}\n`, "utf8");
  return { namespaceCount: namespaceCatalog.length, memberTotal };
}

/* -------------------------------------------------------------------------- */
/*  Themes                                                                    */
/* -------------------------------------------------------------------------- */

async function writeThemes(surface) {
  const { builtInThemes, builtInThemeFonts } = surface;
  const names = Object.keys(builtInThemes);
  const tokenNames = Object.keys(builtInThemes[names[0]]);

  const lines = [
    GENERATED_BANNER("`builtInThemes` + `builtInThemeFonts`"),
    "# Themes & design tokens",
    "",
    `${names.length} built-in themes, ${tokenNames.length} tokens each. Select one with the`,
    "`theme` attribute on `<aktion-app>`, or override individual tokens from inside a program",
    "with `$theme({ … })`.",
    "",
    "```html",
    `<aktion-app theme="corporate"></aktion-app>`,
    "```",
    "",
    "**Never hard-code a colour.** Components already read these tokens, so a program that",
    "picks its own hex values looks wrong the moment the theme changes. If you need a variant,",
    "override the token.",
    "",
    "| theme | web fonts loaded |",
    "| --- | --- |",
    ...names.map(
      (n) =>
        `| \`${n}\` | ${builtInThemeFonts[n]?.import?.length ? builtInThemeFonts[n].import.map((f) => `\`${f}\``).join(", ") : "— (system stack)"} |`,
    ),
    "",
    "A theme selected **by name** pulls in its own web fonts automatically.",
    "",
    "## Token values per theme",
    "",
    `| token | ${names.join(" | ")} |`,
    `| --- | ${names.map(() => "---").join(" | ")} |`,
    ...tokenNames.map(
      (token) =>
        `| \`${token}\` | ${names.map((n) => `\`${cell(builtInThemes[n][token])}\``).join(" | ")} |`,
    ),
    "",
  ];

  await writeFile(resolve(referencesDir, "themes.md"), `${lines.join("\n")}\n`, "utf8");
  return { themeCount: names.length, tokenCount: tokenNames.length };
}

/* -------------------------------------------------------------------------- */
/*  Example gate                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Validate every ```aktion fenced block in the skill against the real library.
 *
 * This gate is the whole reason the replacement can be trusted where its
 * predecessor could not. `coding-gen-skill.md` rotted through two feature waves
 * with **11 of its 22 flagship worked examples failing schema validation** —
 * teaching props that do not exist, which is worse than teaching nothing. The
 * rot was invisible because nothing ever executed those examples.
 *
 * The contract is deliberately strict: a block tagged `aktion` must be a
 * COMPLETE, VALID program. Fragments and illustrative snippets are tagged `js`
 * (or anything else) and are not checked — so the tag is a promise, and a
 * promise that the build keeps.
 */
async function validateExamples(surface) {
  const { getDiagnostics, defaultLibrary } = surface;
  const files = [
    resolve(skillDir, "SKILL.md"),
    ...(await readdir(referencesDir))
      .filter((f) => f.endsWith(".md"))
      .map((f) => resolve(referencesDir, f)),
  ];

  const failures = [];
  let checked = 0;

  for (const file of files) {
    const text = await readFile(file, "utf8");
    const lines = text.split("\n");
    let start = -1;
    let fence = "";

    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i];
      if (start < 0) {
        const open = /^```(\w[\w-]*)\s*$/.exec(line.trim());
        if (open) {
          fence = open[1];
          start = i;
        }
        continue;
      }
      if (line.trim() !== "```") continue;

      if (fence === "aktion") {
        checked += 1;
        const code = lines.slice(start + 1, i).join("\n");
        // Errors block rendering; warnings (e.g. an unknown component) mean the
        // example names something that does not exist, which for teaching
        // material is just as fatal. Gate on both.
        const diagnostics = getDiagnostics(code, defaultLibrary);
        for (const d of diagnostics) {
          failures.push(
            `${file.replace(repoRoot + "/", "")}:${start + 1 + d.line} (example starting line ` +
              `${start + 1}): ${d.severity}: ${d.message}`,
          );
        }
      }
      start = -1;
    }

    if (start >= 0) {
      failures.push(`${file.replace(repoRoot + "/", "")}: unterminated \`\`\`${fence} block at line ${start + 1}`);
    }
  }

  if (failures.length > 0) {
    throw new Error(
      `${failures.length} problem(s) in the skill's \`\`\`aktion examples ` +
        `(${checked} checked). A block tagged \`aktion\` must be a complete, valid program — ` +
        `tag fragments as \`js\` instead.\n\n  ${failures.join("\n  ")}`,
    );
  }

  return { checked };
}

/* -------------------------------------------------------------------------- */

async function main() {
  if (!existsSync(bundlePath)) {
    throw new Error(
      `dist/language.js not found. Run \`npm run build:language\` before \`build:skill\`.`,
    );
  }
  const surface = await import(pathToFileURL(bundlePath).href);

  await mkdir(referencesDir, { recursive: true });

  const components = await writeComponents(surface);
  const builtins = await writeBuiltins(surface);
  const namespaces = await writeNamespaces(surface);
  const themes = await writeThemes(surface);

  // The hand-written half must exist, or the skill ships with dangling links.
  for (const required of ["SKILL.md", "references/patterns.md", "references/gotchas.md"]) {
    if (!existsSync(resolve(skillDir, required))) {
      throw new Error(`skills/aktion/${required} is missing — it is hand-written, not generated.`);
    }
  }

  const written = (await readdir(componentsDir)).length;
  // eslint-disable-next-line no-console
  console.log(
    `Generated skill references: ${components.componentCount} components in ` +
      `${components.groupCount} groups (${written} files), ${builtins.builtinCount} builtins, ` +
      `${namespaces.memberTotal} namespace members, ${themes.themeCount} themes × ` +
      `${themes.tokenCount} tokens`,
  );

  // Runs last: the generated files are on disk, so their examples are checked too.
  const examples = await validateExamples(surface);
  // eslint-disable-next-line no-console
  console.log(`Validated ${examples.checked} \`\`\`aktion examples — all clean`);

  // Surface the SKILL.md counts so a stale hand-written claim is noticed here
  // rather than by a user.
  const skillText = await readFile(resolve(skillDir, "SKILL.md"), "utf8");
  const claimed = skillText.match(/(\d+)\s+components/);
  if (claimed && Number(claimed[1]) !== components.componentCount) {
    throw new Error(
      `skills/aktion/SKILL.md claims ${claimed[1]} components but the library has ` +
        `${components.componentCount}. Update SKILL.md.`,
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
