#!/usr/bin/env node
/**
 * Emit thin entry-point wrappers under `dist/` so the published npm
 * package can be imported without relying on the `exports` map being
 * understood by every bundler / runtime in the wild.
 *
 * Files written:
 *   - `dist/index.js`   — ESM wrapper that re-exports the main bundle.
 *   - `dist/index.cjs`  — CommonJS wrapper around the UMD bundle.
 *   - `dist/index.d.ts` — TypeScript types wrapper pointing at the
 *                         declarations generated by tsc.
 *
 * The bundle filenames (`aktion.js`, `aktion.umd.cjs`, …) are kept
 * unchanged so the CDN URLs documented in the README continue to work.
 */

import { access, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(here, "../dist");

const ESM_WRAPPER = `// Auto-generated by scripts/emit-entry.mjs.
// Re-exports the main bundle so the npm package has a stable
// \`dist/index.js\` entry that works in every bundler.
export * from "./aktion.js";
import "./aktion.js";
`;

const CJS_WRAPPER = `// Auto-generated by scripts/emit-entry.mjs.
// CommonJS shim around the UMD bundle.
module.exports = require("./aktion.umd.cjs");
`;

const DTS_WRAPPER = `// Auto-generated by scripts/emit-entry.mjs.
export * from "./types/index.js";
`;

async function ensureExists(path) {
  try {
    await access(path);
  } catch {
    throw new Error(
      `Expected build artefact not found: ${path}. Run \`vite build\` first.`,
    );
  }
}

async function main() {
  await mkdir(distDir, { recursive: true });

  await ensureExists(resolve(distDir, "aktion.js"));
  await ensureExists(resolve(distDir, "aktion.umd.cjs"));
  await ensureExists(resolve(distDir, "types/index.d.ts"));

  await writeFile(resolve(distDir, "index.js"), ESM_WRAPPER, "utf8");
  await writeFile(resolve(distDir, "index.cjs"), CJS_WRAPPER, "utf8");
  await writeFile(resolve(distDir, "index.d.ts"), DTS_WRAPPER, "utf8");

  // eslint-disable-next-line no-console
  console.log("Wrote dist/index.js, dist/index.cjs, dist/index.d.ts");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
